{% set version = "1.0.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tidygeocoder
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidygeocoder_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidygeocoder/tidygeocoder_{{ version }}.tar.gz
  sha256: 1f2be0e44e3c8d5d90ceadf3fb6bf735f40dd1c82c3d5e7c5ba6f03c332000f5

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-lifecycle
    - r-tibble
    - r-progress
  run:
    - r-base
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-lifecycle
    - r-tibble
    - r-progress

test:
  commands:
    - $R -e "library('tidygeocoder')"           # [not win]
    - "\"%R%\" -e \"library('tidygeocoder')\""  # [win]

about:
  home: https://jessecambon.github.io/tidygeocoder/, https://github.com/jessecambon/tidygeocoder
  license: MIT
  summary: An intuitive interface for getting data from geocoder services.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
